import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Provider from './provider';
import { Outfit } from 'next/font/google';

export const metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
};

const outfit = Outfit({
  subsets: ['latin']
});

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={outfit.className}>
          <Provider>
              <SignedOut>
                <SignInButton />
                <SignUpButton>
                  <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                    Sign Up
                  </button>
                </SignUpButton>
              </SignedOut>
              <SignedIn>
              </SignedIn>
            {children}
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
